export const eventStep = {
  INTRO : "INTRO",
  CREATE_NEW_EVENT: {
    SELECT_EVENT_TYPE: "SELECT_EVENT_TYPE",
    SELECT_EVENT_SIZE: "SELECT_EVENT_SIZE",
    EVENT_FORM: "EVENT_FORM",
    SEND_INVITEE: "SEND_INVITEE",
    FOOD_ARRANGEMENT: "FOOD_ARRANGEMENT",
    ALCOHOL_INCLUDED: "ALCOHOL_INCLUDED",
    DECORATION_REQUIREMENTS: "DECORATION_REQUIREMENTS",
    RENT_BOARD_GAMES: "RENT_BOARD_GAMES"
  }
}